apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: backend
          image: code.addinn-group.com:5050/addinn/digital-software-factory/stage-lab/pfe/2026/dev/digital2026-01/backend/api:develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: DataConnection__Username
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DataConnection__Password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD