/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        // ── App-wide colors (original, used across all pages) ──
        primary: '#00288e',
        secondary: '#712ae2',
        tertiary: '#003d27',
        // ── Landing-page-only colors ──
        'lp-primary': '#2563EB',
        'lp-secondary': '#7C3AED',
        'lp-tertiary': '#DB2777',
        'surface': '#f9f9ff',
        'surface-container': '#e7eeff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-variant': '#d8e3fb',
        'secondary-container': '#8a4cfc',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#173bab',
        'on-primary-fixed': '#001453',
        'on-primary-container': '#a8b8ff',
        'primary-container': '#1e40af',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b8c4ff',
        'outline-variant': '#c4c5d5',
        'outline': '#757684',
        'background': '#f9f9ff',
        'on-background': '#111c2d',
        'on-secondary-fixed': '#25005a',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#eaddff',
        'secondary-fixed-dim': '#d2bbff',
        'secondary-dim': '#8B5CF6',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-surface': '#111c2d',
        'on-surface-variant': '#444653',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#3fd298',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        'tertiary-container': '#00563a',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'inverse-on-surface': '#ecf1ff',
        'inverse-primary': '#b8c4ff',
        'inverse-surface': '#263143',
        'primary-dim': '#3B82F6',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      keyframes: {
        pulse: {
          '0%': { boxShadow: '0 0 0 0 rgba(124, 58, 237, 0.4)' },
          '70%': { boxShadow: '0 0 0 10px rgba(124, 58, 237, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(124, 58, 237, 0)' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      animation: {
        'pulse-dot': 'pulse 2s infinite',
        'fade-in-up': 'fade-in-up 0.6s ease-out forwards',
        float: 'float 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}

