apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  DataConnection__Hostname: "postgres"
  DataConnection__Database: "TestAutomation_Db"
  Jwt__Issuer: "TestApi"
  Jwt__Audience: "TestApiUsers"
