"""
Service d'execution des tests generes.
Lance les scripts Playwright et collecte les resultats step par step
avec captures d'ecran.

Day 12 enhancement:
- Visual fallback: quand un locator Playwright echoue, on prend un screenshot,
  on lance detect_from_page() (YOLO + DOM hybride), on trouve l'element le plus
  proche du texte cible et on execute l'action via coordonnees souris.
- Cela permet a l'agent de tester des pages sans attributs d'accessibilite.

Day 13 enhancements:
- Retries: max 2 tentatives par etape avant FAILED (configurable via MAX_RETRIES)
- Screenshot apres chaque etape (configurable via STEP_SCREENSHOT)
- Timeouts: networkidle + waitForSelector avec STEP_TIMEOUT_MS / NETWORKIDLE_TIMEOUT_MS
- Cookie popup: detection + fermeture automatique apres chaque navigation
- Modales inattendues: Escape + bouton "fermer" / "close"
- Smart wait: attente que l'element soit stable (visible + enabled) avant interaction

Day 14/15 enhancements:
- Integration AdaptationService : diagnostique l'erreur → strategie corrective
- RecoveryStats : taux de recuperation mesure a chaque execution
- StepResult enrichi : retry_count, visual_fallback_used, adaptation_appliquee
"""

import difflib
import asyncio
import logging
import os
import re
import time
import uuid
from datetime import datetime
from typing import Optional

from playwright.async_api import async_playwright, expect, Page, Browser, TimeoutError as PwTimeoutError

from app.schemas.test_schemas import (
    TestExecutionRequest,
    TestExecutionResponse,
    StepResult,
    RecoveryStats,
    FallbackTrace,
    DetectionCandidate,
)
from app.config import settings

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Custom exception to carry retry metadata out of _exec_with_retry
# ---------------------------------------------------------------------------

class _StepFailedError(Exception):
    """
    Raised when a step fails after all retries.

    Carries retry metadata so the caller can record accurate stats
    even for ultimately-failed steps:
      - retry_count     : number of retry attempts made (0 = only 1 attempt)
      - fallback_tried  : True if visual fallback was attempted at least once
      - fallback_trace  : FallbackTrace from the *last* fallback attempt (if any)
      - playwright_error: the original Playwright locator error message
    """
    def __init__(
        self,
        original: Exception,
        retry_count: int,
        fallback_tried: bool,
        fallback_trace: Optional["FallbackTrace"] = None,
        playwright_error: str = "",
    ):
        self.original = original
        self.retry_count = retry_count
        self.fallback_tried = fallback_tried
        self.fallback_trace = fallback_trace
        self.playwright_error = playwright_error or str(original)
        super().__init__(str(original))


# ---------------------------------------------------------------------------
# Visual-fallback helpers (module-level, no class dependency)
# ---------------------------------------------------------------------------

def _parse_target_from_line(line: str) -> Optional[str]:
    """Extrait le texte cible d'une ligne Playwright pour le fallback visuel.

    Returns:
        str  — text label extracted (can be empty string for type-only fallback)
        None — line has no actionable locator (e.g. wait_for_load_state)
    """
    patterns = [
        r'get_by_label\("([^"]+)"\)',
        r'get_by_placeholder\("([^"]+)"\)',
        r'get_by_text\("([^"]+)"\)',
        r'get_by_role\([^,]+,\s*name="([^"]+)"\)',
        r'filter\(has_text="([^"]+)"\)',
    ]
    for pat in patterns:
        m = re.search(pat, line)
        if m:
            return m.group(1)
    # locator("css") — extract meaningful CSS target; "body" is a no-op placeholder.
    # The regex handles both single-quoted and escaped-double-quoted attribute values
    # e.g.  locator("select[id='foo']")
    #        locator("select[id=\"foo\"]")
    m = re.search(r'locator\("((?:[^"\\]|\\.)*)"', line)
    if m:
        sel = m.group(1)
        if sel in ("body",):
            return None
        # For compound CSS attribute selectors generated by the generator
        # (e.g. "input[name='Email' i], input[id='Email' i]..."),
        # extract the first attribute *value* as the meaningful text label so
        # _find_best_element can score against 'Email' instead of '' — which
        # would cause it to blindly pick the first input_text on the page.
        attr_val_m = re.search(
            r"\[(?:name|id|placeholder|aria-label)=['\"]([^'\"]+)['\"]",
            sel,
        )
        if attr_val_m:
            return attr_val_m.group(1)  # e.g. "Email"
        # For selectors like input[type='email'], extract the type value as a
        # semantic hint: DOM enrichment often stores 'userEmail name@example.com'
        # which contains 'email' — enough for similarity matching to win.
        type_val_m = re.search(r"\[type=['\"]([^'\"]+)['\"]", sel)
        if type_val_m:
            return type_val_m.group(1)  # e.g. 'email', 'password', 'text'
        # CSS selector present but no extractable label → type-only fallback
        return ""
    return None


def _intended_types_from_line(line: str) -> list[str]:
    """Determine les types YOLO pertinents pour une action donnee."""
    if ".fill(" in line or ".clear()" in line:
        return ["input_text", "input_password"]
    if ".check()" in line or ".uncheck()" in line:
        return ["checkbox"]
    if ".select_option(" in line:
        return ["dropdown"]
    if ".click()" in line or ".click(" in line or ".hover()" in line:
        return ["button", "link", "checkbox", "dropdown"]
    return []


def _score_candidates(elements, target: str, type_filter: list[str]):
    """
    Score every detected element against `target` for visual fallback.

    Returns
    -------
    list[tuple[DetectedElement, float]]   sorted by score DESC
        Every input element is included so the caller (FallbackTrace)
        can show all candidates considered.
    """
    target_lower = target.lower()

    candidates = [e for e in elements if not type_filter or e.type in type_filter]
    if not candidates:
        candidates = list(elements)

    scored: list[tuple] = []
    for elem in candidates:
        text = (elem.texte_ocr or elem.label or "").lower()
        if not text:
            score = 0.1  # type-only base score
        else:
            score = difflib.SequenceMatcher(None, target_lower, text).ratio()
            if target_lower and target_lower in text:
                score += 0.3  # substring bonus
        scored.append((elem, score))

    # Sort by score DESC; break ties using YOLO confidence DESC so that the
    # highest-confidence detection of a given type wins when scores are equal.
    scored.sort(key=lambda t: (t[1], t[0].confiance_detection), reverse=True)
    return scored


def _find_best_element(elements, target: str, type_filter: list[str]):
    """Trouve l'element detecte le mieux correspondant au texte cible."""
    scored = _score_candidates(elements, target, type_filter)
    if not scored:
        return None

    best, best_score = scored[0]

    # Good text similarity → accept immediately.
    if best_score > 0.25:
        return best

    # Pure type-only lookup (no target text specified → return first type match).
    if not target:
        return best

    # Target IS specified but every candidate scored ≤ 0.1 — meaning no element
    # had any readable text at all (OCR failed AND DOM enrichment was empty).
    # Accept the first type-matched candidate as a last resort, since we literally
    # have no text signal to do better.
    if bool(type_filter) and best is not None and best.type in type_filter:
        all_type_only = all(s <= 0.1 for _, s in scored)
        if all_type_only:
            return best  # last resort: accept first type-matched element

    return None


class ExecutorService:
    """Service d'execution des scripts de test Playwright."""

    def __init__(self):
        self._vision = None       # Lazy-loaded VisionService
        self._adaptation = None   # Lazy-loaded AdaptationService

    def _get_vision(self):
        """Charge VisionService une seule fois (evite les imports circulaires)."""
        if self._vision is None:
            from app.services.vision_service import VisionService  # noqa: PLC0415
            self._vision = VisionService()
        return self._vision

    def _get_adaptation(self):
        """Charge AdaptationService une seule fois."""
        if self._adaptation is None:
            from app.services.adaptation_service import AdaptationService  # noqa: PLC0415
            self._adaptation = AdaptationService()
        return self._adaptation

    @staticmethod
    def _compute_recovery_stats(results: list[StepResult]) -> RecoveryStats:
        """Calcule les statistiques de recuperation a partir des step results."""
        total = len(results)
        ok_first = sum(1 for r in results if r.statut == "OK" and r.retry_count == 0 and not r.visual_fallback_used)
        recovered = sum(1 for r in results if r.statut == "OK" and (r.retry_count > 0 or r.visual_fallback_used))
        failed = sum(1 for r in results if r.statut == "FAILED")
        visual_total = sum(1 for r in results if r.visual_fallback_used)
        adapt_total = sum(1 for r in results if r.adaptation_appliquee)
        denominator = recovered + failed
        taux = round(recovered / denominator, 3) if denominator > 0 else 1.0
        return RecoveryStats(
            steps_total=total,
            steps_ok=ok_first,
            steps_recovered=recovered,
            steps_failed=failed,
            taux_recuperation=taux,
            visual_fallback_total=visual_total,
            adaptation_total=adapt_total,
        )

    async def execute(self, request: TestExecutionRequest) -> TestExecutionResponse:
        """Execute un test et renvoie les resultats detailles."""
        test_id = uuid.uuid4().hex[:12]
        self._current_test_id = test_id
        self._current_step_idx = 0
        start = time.time()
        steps_results: list[StepResult] = []
        screenshots: list[str] = []

        os.makedirs(settings.SCREENSHOTS_DIR, exist_ok=True)

        # When headless=False (Watch Run), Playwright needs a display.
        # Prefer the host X11 display forwarded via the DISPLAY env var
        # (set in docker-compose.yml via X11 socket mount).  If no host
        # display is available, fall back to a local Xvfb virtual display.
        headless = request.headless if request.headless is not None else settings.HEADLESS
        xvfb_proc = None
        if not headless:
            if not os.environ.get("DISPLAY"):
                # No host display forwarded — try Xvfb as last resort.
                import subprocess, shutil
                if shutil.which("Xvfb"):
                    display = ":99"
                    xvfb_proc = subprocess.Popen(
                        ["Xvfb", display, "-screen", "0", "1280x720x24", "-ac"],
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                    os.environ["DISPLAY"] = display
            # else: DISPLAY is already set from X11 forwarding — use it directly.

        try:
            result = await self._execute_internal(request, test_id, headless, steps_results, screenshots, start)
        finally:
            if xvfb_proc is not None:
                xvfb_proc.terminate()
                xvfb_proc.wait()
        return result

    async def _execute_internal(self, request, test_id, headless, steps_results, screenshots, start) -> TestExecutionResponse:
        async with async_playwright() as pw:
            browser = await pw.chromium.launch(
                headless=headless,
                slow_mo=settings.SLOW_MO_MS,
            )
            page = await browser.new_page()
            # Apply configured timeout so locator failures surface in STEP_TIMEOUT_MS
            # (not Playwright's 30s default). This is critical: without this, every
            # failed locator burns 30s before the visual DOM fallback can run.
            page.set_default_timeout(settings.STEP_TIMEOUT_MS)

            # Navigate to the target URL first
            if request.url_cible:
                step_start = time.time()
                try:
                    await page.goto(request.url_cible, timeout=15_000)
                    await page.wait_for_load_state(
                        "networkidle", timeout=settings.NETWORKIDLE_TIMEOUT_MS
                    )
                    # Day 13: auto-close cookie banners after navigation
                    await self._handle_cookie_popup(page)
                    steps_results.append(StepResult(
                        step=f"Navigate to {request.url_cible}",
                        statut="OK",
                        duree_ms=round((time.time() - step_start) * 1000, 1),
                    ))
                except Exception as e:
                    steps_results.append(StepResult(
                        step=f"Navigate to {request.url_cible}",
                        statut="FAILED",
                        duree_ms=round((time.time() - step_start) * 1000, 1),
                        erreur=str(e),
                    ))
                # Capture initial screenshot
                ss = await self._screenshot(page, test_id, "initial")
                if ss:
                    screenshots.append(ss)

            # Execute the generated script line by line
            if request.script_code:
                result, step_results_exec, ss_list = await self._execute_script(
                    page, request.script_code, test_id,
                    already_navigated_url=request.url_cible or "",
                )
                steps_results.extend(step_results_exec)
                screenshots.extend(ss_list)

            await browser.close()

        total_ms = (time.time() - start) * 1000
        any_failed = any(s.statut == "FAILED" for s in steps_results)
        recovery_stats = self._compute_recovery_stats(steps_results)

        return TestExecutionResponse(
            test_id=test_id,
            scenario_name=request.scenario_name,
            statut="FAILED" if any_failed else "PASSED",
            duree_ms=round(total_ms, 1),
            steps_results=steps_results,
            screenshots=screenshots,
            recovery_stats=recovery_stats,
        )

    async def execute_live(
        self,
        page: Page,
        steps: list[dict],
        test_id: str,
    ) -> tuple[list[StepResult], list[str]]:
        """Execute des steps sur une page deja ouverte (pour le pipeline)."""
        results: list[StepResult] = []
        screenshots: list[str] = []
        self._current_test_id = test_id
        self._current_step_idx = 0

        for i, step in enumerate(steps, 1):
            step_start = time.time()
            code_lines = step.get("lines", [])
            comment = step.get("comment", f"Step {i}")
            total_retries = 0
            total_visual = False
            total_adapt = ""
            step_trace: Optional[FallbackTrace] = None
            step_pw_err = ""

            try:
                for line in code_lines:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    rc, vu, ad, tr, pw = await self._exec_with_retry(page, line)
                    total_retries += rc
                    total_visual = total_visual or vu
                    total_adapt = total_adapt or ad
                    if tr is not None:
                        step_trace = tr
                    if pw:
                        step_pw_err = pw

                elapsed = round((time.time() - step_start) * 1000, 1)
                results.append(StepResult(
                    step=comment, statut="OK", duree_ms=elapsed,
                    retry_count=total_retries, visual_fallback_used=total_visual,
                    adaptation_appliquee=total_adapt,
                    fallback_trace=step_trace,
                    playwright_error=step_pw_err,
                ))
            except _StepFailedError as sfe:
                elapsed = round((time.time() - step_start) * 1000, 1)
                results.append(StepResult(
                    step=comment, statut="FAILED", duree_ms=elapsed,
                    erreur=str(sfe.original),
                    retry_count=sfe.retry_count,
                    visual_fallback_used=sfe.fallback_tried,
                    fallback_trace=sfe.fallback_trace or step_trace,
                    playwright_error=sfe.playwright_error or step_pw_err,
                ))
            except Exception as e:
                elapsed = round((time.time() - step_start) * 1000, 1)
                results.append(StepResult(
                    step=comment, statut="FAILED", duree_ms=elapsed, erreur=str(e)
                ))

            # Day 13: screenshot after EVERY step (configurable)
            if settings.STEP_SCREENSHOT:
                ss = await self._screenshot(page, test_id, f"step_{i}")
                if ss:
                    screenshots.append(ss)

        return results, screenshots

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    async def _execute_script(
        self, page: Page, script_code: str, test_id: str,
        already_navigated_url: str = "",
    ) -> tuple[str, list[StepResult], list[str]]:
        """Execute embedded Playwright commands from generated script.

        Args:
            already_navigated_url: If set, the FIRST `await page.goto(URL)` line
                whose URL matches this value is silently skipped — prevents the
                Gherkin `Given I navigate to URL` step from re-navigating after
                `execute()` already used `request.url_cible`. The skipped step
                still appears in results as OK so the user sees their step ran.
        """
        results: list[StepResult] = []
        screenshots: list[str] = []

        # Extract executable lines from the script (lines with 'await page.' or 'await expect').
        # Skip lines that are inside helper function definitions — those contain variables
        # like `path`, `frame_name` that are undefined at the top level and would cause
        # spurious FAILED steps.
        lines = script_code.splitlines()
        exec_blocks: list[tuple[str, str]] = []  # (comment, code_line)
        current_comment = ""
        inside_helper_func = False  # True while inside a def _xxx() helper body

        for line in lines:
            stripped = line.strip()

            # Detect entry into a helper function definition (starts at column 0, name starts with _)
            if re.match(r"^async def _\w+\(|^def _\w+\(", line):
                inside_helper_func = True
                continue
            # Detect entry into the main test function — stop skipping
            if re.match(r"^async def test_\w+\(|^async def \w+\(", line):
                inside_helper_func = False
                continue
            # A non-indented non-empty, non-comment line closes any helper scope
            if line and not line[0].isspace() and not stripped.startswith("#"):
                inside_helper_func = False

            if inside_helper_func:
                continue  # skip everything inside helper function bodies

            if stripped.startswith("#") and re.search(r"[Ss]tep\s+\d+", stripped):
                # Handles both "# Step N:" and "# ── Step N:" (template uses em-dashes)
                current_comment = re.sub(r"^#\s*\u2500*\s*\u2014*\s*\u2212*\s*[-─]*\s*", "", stripped)
                current_comment = re.sub(r"\s*[-─\u2500]+\s*$", "", current_comment).strip()
            elif (
                ("await page." in stripped or "await expect" in stripped
                 or stripped.startswith("assert "))
                and not stripped.startswith("#")  # skip commented-out placeholder lines
            ):
                # Only collect lines that belong to a named step (after a # ── Step N: comment).
                # Lines before the first step comment are part of the generated script's
                # preamble/initial-navigation block — the executor already handled navigation
                # via url_cible, so those would cause duplicates in the results.
                # `assert ...` lines are emitted by strict-assertion generation
                # (dropdown selected-value, login success URL check, visible-text match).
                if current_comment:
                    exec_blocks.append((current_comment, stripped))
            elif stripped.startswith("loc = ") or stripped.startswith("locator = "):
                exec_blocks.append((current_comment or stripped, stripped))

        step_num = 0
        # Pre-compile a regex to extract the URL string from `await page.goto("...")`
        _goto_url_re = re.compile(r'await\s+page\.goto\(\s*["\']([^"\']+)["\']')

        # ── Group consecutive lines by their step comment so a single Gherkin
        # step that emits multiple await lines (e.g. `naviguer` emits goto +
        # wait_for_load_state) shows up as ONE StepResult, not N. ──────────
        grouped: list[tuple[str, list[str]]] = []
        for c, code in exec_blocks:
            if grouped and grouped[-1][0] == c:
                grouped[-1][1].append(code)
            else:
                grouped.append((c, [code]))

        skipped_initial_goto = False
        for comment, codes in grouped:
            step_num += 1
            step_start = time.time()

            # ── Skip duplicate navigate ──────────────────────────────────
            # If `execute()` already navigated to `already_navigated_url`,
            # and the FIRST step's first line is `page.goto(SAME_URL)`,
            # report the whole step as OK without re-running it. Avoids
            # the "Step 1 appears twice" symptom in the report.
            if (
                not skipped_initial_goto
                and already_navigated_url
                and codes
                and "page.goto(" in codes[0]
            ):
                m = _goto_url_re.search(codes[0])
                if m and m.group(1).rstrip("/") == already_navigated_url.rstrip("/"):
                    skipped_initial_goto = True
                    elapsed = round((time.time() - step_start) * 1000, 1)
                    results.append(StepResult(
                        step=comment, statut="OK", duree_ms=elapsed,
                    ))
                    if settings.STEP_SCREENSHOT:
                        ss = await self._screenshot(page, test_id, f"step_{step_num}")
                        if ss:
                            screenshots.append(ss)
                    continue

            # ── Execute every line in this step; first failure stops the group
            total_retry = 0
            total_visual = False
            total_adapt = ""
            step_trace: Optional[FallbackTrace] = None
            step_pw_err = ""
            failure: Exception | None = None
            failure_is_step_error = False

            for code in codes:
                try:
                    r, v, a, tr, pw = await self._exec_with_retry(page, code)
                    total_retry += r
                    total_visual = total_visual or v
                    total_adapt = total_adapt or a
                    if tr is not None:
                        step_trace = tr
                    if pw:
                        step_pw_err = pw
                except _StepFailedError as sfe:
                    failure = sfe
                    failure_is_step_error = True
                    total_retry = max(total_retry, sfe.retry_count)
                    total_visual = total_visual or sfe.fallback_tried
                    if sfe.fallback_trace is not None:
                        step_trace = sfe.fallback_trace
                    if sfe.playwright_error:
                        step_pw_err = sfe.playwright_error
                    break
                except Exception as e:
                    failure = e
                    break

            elapsed = round((time.time() - step_start) * 1000, 1)
            if failure is None:
                results.append(StepResult(
                    step=comment, statut="OK", duree_ms=elapsed,
                    retry_count=total_retry, visual_fallback_used=total_visual,
                    adaptation_appliquee=total_adapt,
                    fallback_trace=step_trace,
                    playwright_error=step_pw_err,
                ))
            elif failure_is_step_error:
                sfe = failure  # type: ignore[assignment]
                results.append(StepResult(
                    step=comment, statut="FAILED", duree_ms=elapsed,
                    erreur=str(sfe.original),
                    retry_count=sfe.retry_count,
                    visual_fallback_used=sfe.fallback_tried,
                    fallback_trace=sfe.fallback_trace or step_trace,
                    playwright_error=sfe.playwright_error or step_pw_err,
                ))
            else:
                results.append(StepResult(
                    step=comment, statut="FAILED", duree_ms=elapsed,
                    erreur=str(failure),
                ))

            # Screenshot once per step (not once per await line)
            if settings.STEP_SCREENSHOT:
                ss = await self._screenshot(page, test_id, f"step_{step_num}")
                if ss:
                    screenshots.append(ss)

        overall = "PASSED" if all(r.statut == "OK" for r in results) else "FAILED"
        return overall, results, screenshots

    async def _exec_with_retry(
        self, page: Page, line: str
    ) -> tuple[int, bool, str, Optional[FallbackTrace], str]:
        """
        Execute une ligne Playwright avec retries + AdaptationService (Day 14/15).

        Retourne (retry_count, visual_fallback_used, adaptation_appliquee,
                  fallback_trace, playwright_error).
        """
        last_exc: Exception = Exception("No attempt made")
        visual_used = False
        fallback_tried = False
        adaptation_str = ""
        last_trace: Optional[FallbackTrace] = None
        last_pw_error = ""

        for attempt in range(1, settings.MAX_RETRIES + 2):  # 1 + up to 2 retries
            if page.is_closed():
                last_exc = RuntimeError("Playwright page is closed — aborting step")
                last_pw_error = "PageClosed: page was closed before attempt"
                break
            try:
                visual_success, attempted, trace, pw_err = (
                    await self._exec_line_with_fallback_tracked(page, line)
                )
                fallback_tried = fallback_tried or attempted
                visual_used = visual_used or visual_success
                if trace is not None:
                    last_trace = trace
                if pw_err:
                    last_pw_error = pw_err
                return attempt - 1, visual_used, adaptation_str, last_trace, last_pw_error
            except _StepFailedError as sfe:
                fallback_tried = True
                last_exc = sfe.original
                if sfe.fallback_trace is not None:
                    last_trace = sfe.fallback_trace
                if sfe.playwright_error:
                    last_pw_error = sfe.playwright_error
                e = sfe.original
                # Assertions (expect/assert lines) must NOT be adapted away —
                # that would turn a real failure into a false PASS.
                stripped = line.strip()
                is_assertion_line = (
                    stripped.startswith("await expect(")
                    or stripped.startswith("expect(")
                    or stripped.startswith("assert ")
                )
                if is_assertion_line:
                    break  # propagate as failure immediately, no retry
                if attempt <= settings.MAX_RETRIES:
                    delay_ms = 500 * (2 ** (attempt - 1))
                    logger.warning(
                        "Step attempt %d/%d failed (fallback tried, %s) — getting adaptation strategy…",
                        attempt, settings.MAX_RETRIES + 1, e,
                    )
                    if page.is_closed():
                        break
                    adaptation_str = await self._run_adaptation(page, e, line, adaptation_str)
                    if not page.is_closed():
                        await page.wait_for_timeout(delay_ms)
                        await self._handle_unexpected_modal(page)
            except Exception as e:
                last_exc = e
                if attempt <= settings.MAX_RETRIES:
                    delay_ms = 500 * (2 ** (attempt - 1))
                    logger.warning(
                        "Step attempt %d/%d failed (%s) — getting adaptation strategy…",
                        attempt, settings.MAX_RETRIES + 1, e,
                    )

                    # ── AdaptationService diagnosis ──────────────────────────
                    try:
                        from app.schemas.test_schemas import AdaptationRequest  # noqa: PLC0415
                        screenshot_b64 = ""
                        try:
                            ss_bytes = await page.screenshot()
                            import base64  # noqa: PLC0415
                            screenshot_b64 = base64.b64encode(ss_bytes).decode()
                        except Exception:
                            pass

                        adapt_req = AdaptationRequest(
                            type_erreur=type(e).__name__ + ": " + str(e)[:200],
                            step_en_cours={"line": line},
                            screenshot_actuel=screenshot_b64,
                        )
                        adapt_resp = self._get_adaptation().adapt(adapt_req)
                        adaptation_str = adapt_resp.strategie or adaptation_str
                        logger.info(
                            "Adaptation strategy: %s (conf=%.2f)",
                            adapt_resp.strategie, adapt_resp.confiance,
                        )

                        for action in adapt_resp.actions_correctives:
                            if action.action == "press_escape":
                                await self._handle_unexpected_modal(page)
                                break
                            elif action.action in ("click", "cookie_close"):
                                await self._handle_cookie_popup(page)
                                break
                            elif action.action == "screenshot_and_redetect":
                                pass
                    except Exception as adapt_err:
                        logger.debug("AdaptationService error: %s", adapt_err)

                    await page.wait_for_timeout(delay_ms)
                    await self._handle_unexpected_modal(page)

        raise _StepFailedError(
            last_exc,
            retry_count=settings.MAX_RETRIES,
            fallback_tried=fallback_tried,
            fallback_trace=last_trace,
            playwright_error=last_pw_error,
        )

    async def _run_adaptation(self, page: Page, exc: Exception, line: str, adaptation_str: str) -> str:
        """Run AdaptationService and apply first corrective action. Returns updated strategy str."""
        try:
            from app.schemas.test_schemas import AdaptationRequest  # noqa: PLC0415
            screenshot_b64 = ""
            try:
                ss_bytes = await page.screenshot()
                import base64  # noqa: PLC0415
                screenshot_b64 = base64.b64encode(ss_bytes).decode()
            except Exception:
                pass

            adapt_req = AdaptationRequest(
                type_erreur=type(exc).__name__ + ": " + str(exc)[:200],
                step_en_cours={"line": line},
                screenshot_actuel=screenshot_b64,
            )
            adapt_resp = self._get_adaptation().adapt(adapt_req)
            new_strategy = adapt_resp.strategie or adaptation_str
            logger.info("Adaptation strategy: %s (conf=%.2f)", adapt_resp.strategie, adapt_resp.confiance)

            for action in adapt_resp.actions_correctives:
                if action.action == "press_escape":
                    await self._handle_unexpected_modal(page)
                    break
                elif action.action in ("click", "cookie_close"):
                    await self._handle_cookie_popup(page)
                    break
            return new_strategy
        except Exception as adapt_err:
            logger.debug("AdaptationService error: %s", adapt_err)
            return adaptation_str

    # ------------------------------------------------------------------
    # Day 13: Cookie popup & modal handlers
    # ------------------------------------------------------------------

    # Common accept / reject button texts for cookie banners (FR + EN).
    # Kept INTENTIONALLY narrow — matching too-generic words like "ok",
    # "continuer" or "fermer" used to click form buttons mid-test and
    # caused the dreaded "Target page, context or browser has been closed"
    # because the click triggered an unintended navigation/form submission.
    _COOKIE_ACCEPT_TEXTS = [
        "accept all cookies", "accept all", "accept cookies",
        "allow all cookies", "allow cookies", "allow all",
        "i accept", "agree to all", "i agree",
        "accepter tous les cookies", "accepter les cookies",
        "tout accepter", "j'accepte les cookies", "j'accepte tout",
    ]

    async def _handle_cookie_popup(self, page: Page) -> bool:
        """
        Detecte et ferme les bannieres de cookies apres navigation.

        Conservative on purpose: only acts when a cookie/consent banner is
        clearly visible (text contains 'cookie', 'consent' or 'privacy'),
        and silently aborts if the page has been closed.
        """
        if page.is_closed():
            return False
        try:
            page_text = (await page.evaluate(
                "() => (document.body && document.body.innerText) ? document.body.innerText.slice(0, 4000).toLowerCase() : ''"
            )) or ""
        except Exception:
            return False
        if not any(kw in page_text for kw in ("cookie", "consent", "privacy", "confidentialit")):
            return False  # No cookie banner detected — do not click random buttons.

        for text in self._COOKIE_ACCEPT_TEXTS:
            try:
                btn = page.get_by_role("button", name=re.compile(text, re.IGNORECASE))
                if await btn.count() > 0:
                    await btn.first.click(timeout=2_000)
                    await page.wait_for_timeout(300)
                    logger.info("Cookie popup closed via button: '%s'", text)
                    return True
            except Exception:
                continue
        for text in ["accepter les cookies", "accept cookies", "i accept", "agree"]:
            try:
                lnk = page.get_by_role("link", name=re.compile(text, re.IGNORECASE))
                if await lnk.count() > 0:
                    await lnk.first.click(timeout=2_000)
                    await page.wait_for_timeout(300)
                    logger.info("Cookie popup closed via link: '%s'", text)
                    return True
            except Exception:
                continue
        return False

    # Modal close-button patterns (aria-label or text)
    _MODAL_CLOSE_LABELS = [
        "close", "fermer", "dismiss", "×", "✕", "cancel", "annuler",
    ]

    async def _handle_unexpected_modal(self, page: Page) -> bool:
        """
        Gere les modales inattendues : presse Escape uniquement.

        Auparavant cliquait aussi sur n'importe quel bouton 'cancel' / 'fermer',
        ce qui annulait des formulaires en plein test et faisait fermer la
        page. On se contente desormais d'Escape, qui est inoffensif.
        """
        if page.is_closed():
            return False
        try:
            await page.keyboard.press("Escape")
            await page.wait_for_timeout(150)
            return True
        except Exception:
            return False

    async def _smart_wait_for_element(
        self, page: Page, selector: str, timeout_ms: Optional[int] = None
    ) -> bool:
        """
        Attend intelligemment qu'un element soit visible et interactif.

        1. wait_for_selector (visible state)
        2. Wait until not disabled
        Retourne True si l'element est pret, False sinon.
        """
        t = timeout_ms or settings.STEP_TIMEOUT_MS
        try:
            await page.wait_for_selector(selector, state="visible", timeout=t)
            # Additional check: wait until enabled
            locator = page.locator(selector)
            end = time.monotonic() + t / 1000
            while time.monotonic() < end:
                try:
                    disabled = await locator.is_disabled(timeout=500)
                    if not disabled:
                        return True
                except Exception:
                    return True  # element gone — assume interaction succeeded
                await page.wait_for_timeout(150)
            return False
        except PwTimeoutError:
            logger.debug("smart_wait_for_element timed out for selector: %s", selector)
            return False

    # ------------------------------------------------------------------
    async def _exec_line_with_fallback_tracked(
        self, page: Page, line: str
    ) -> tuple[bool, bool, Optional[FallbackTrace], str]:
        """
        Execute 'line' with visual-fallback safety net.

        Returns
        -------
        (visual_success, fallback_attempted, fallback_trace, playwright_error)
            visual_success    – True if visual fallback was used AND succeeded
            fallback_attempted – True if visual fallback was tried (even if it failed)
            fallback_trace    – diagnostic data from the fallback attempt (or None)
            playwright_error  – original locator error message (or "")
        """
        try:
            await self._exec_line(page, line)
            return False, False, None, ""
        except Exception as original_error:
            target = _parse_target_from_line(line)
            pw_error = f"{type(original_error).__name__}: {str(original_error)[:300]}"
            # Visual fallback can ONLY recover interactive actions
            # (click / fill / hover / check / select). It is structurally
            # meaningless for assertions like `expect(...).to_be_visible()`
            # or `to_contain_text(...)` — clicking pixels cannot make a
            # missing text appear. Skip the (expensive) YOLO+DOM scan in
            # that case and let the original error propagate verbatim.
            stripped = line.strip()
            is_assertion = (
                stripped.startswith("await expect(")
                or stripped.startswith("expect(")
                or stripped.startswith("assert ")
            )
            if is_assertion:
                raise _StepFailedError(
                    original_error, retry_count=0, fallback_tried=False,
                    fallback_trace=None, playwright_error=pw_error,
                )
            # None  → no locator in this line at all (e.g. wait_for_load_state) → skip
            # ""    → locator found but no text label → type-only fallback
            # "foo" → text label extracted → text + type fallback
            if target is not None:
                trace = await self._visual_fallback(page, line, target)
                if trace.success:
                    logger.info("Visual fallback succeeded for: %s", line.strip())
                    return True, True, trace, pw_error
                # Fallback was attempted but couldn't recover
                raise _StepFailedError(
                    original_error, retry_count=0, fallback_tried=True,
                    fallback_trace=trace, playwright_error=pw_error,
                )
            raise original_error

    async def _exec_line_with_fallback(self, page: Page, line: str):
        """Execute a Playwright line; fall back to visual detection on locator failure."""
        await self._exec_line_with_fallback_tracked(page, line)

    async def _visual_fallback(self, page: Page, line: str, target: str) -> FallbackTrace:
        """
        Fallback visuel : screenshot → YOLO+DOM detection → click/fill aux coordonnees.

        Returns a fully-populated FallbackTrace describing what was detected,
        which candidate won (or none), and whether the action succeeded.
        Saves both raw and annotated screenshots for the diagnostic report.
        """
        type_filter = _intended_types_from_line(line)
        trace = FallbackTrace(target_text=target, type_filter=type_filter)

        try:
            screenshot_bytes = await page.screenshot()
            vision = self._get_vision()
            detection, yolo_raw, dom_raw = await vision.detect_from_page_with_breakdown(
                page, screenshot_bytes
            )

            trace.yolo_count = len(yolo_raw)
            trace.dom_count = len(dom_raw)
            trace.merged_count = len(detection.elements)

            scored = _score_candidates(detection.elements, target, type_filter)
            # Top-15 candidates are enough for a UI table; full list is rarely useful
            top_n = scored[:15]
            for rank, (elem, score) in enumerate(top_n, 1):
                bb = elem.bounding_box
                trace.candidates.append(DetectionCandidate(
                    rank=rank,
                    type=elem.type,
                    label=(elem.label or "")[:120],
                    source=elem.source,
                    confiance_detection=float(elem.confiance_detection),
                    similarity_score=round(float(score), 3),
                    bbox_x=bb.x, bbox_y=bb.y, bbox_w=bb.width, bbox_h=bb.height,
                    texte_ocr=(elem.texte_ocr or "")[:120],
                    was_chosen=False,
                ))

            elem = _find_best_element(detection.elements, target, type_filter)

            # Persist screenshots regardless of outcome — they're invaluable
            # for diagnosing *why* fallback failed.
            test_id = getattr(self, "_current_test_id", "step")
            step_idx = getattr(self, "_current_step_idx", 0)
            self._current_step_idx = step_idx + 1  # auto-increment per fallback
            raw_path = ""
            ann_path = ""
            try:
                os.makedirs(settings.SCREENSHOTS_DIR, exist_ok=True)
                raw_path = os.path.join(
                    settings.SCREENSHOTS_DIR,
                    f"{test_id}_fb{step_idx}_raw.png",
                )
                with open(raw_path, "wb") as f:
                    f.write(screenshot_bytes)
                from app.services.vision_service import VisionService  # noqa: PLC0415
                annotated_bytes = VisionService.annotate_screenshot(
                    screenshot_bytes, yolo_raw, dom_raw, winner=elem
                )
                ann_path = os.path.join(
                    settings.SCREENSHOTS_DIR,
                    f"{test_id}_fb{step_idx}_annotated.png",
                )
                with open(ann_path, "wb") as f:
                    f.write(annotated_bytes)
            except Exception as ss_err:
                logger.debug("Failed to save fallback screenshots: %s", ss_err)
            trace.screenshot_raw = raw_path
            trace.screenshot_annotated = ann_path

            if elem is None:
                logger.debug("Visual fallback: no matching element for '%s'", target)
                trace.success = False
                return trace

            # Mark winner in candidates list
            for c in trace.candidates:
                if (
                    c.bbox_x == elem.bounding_box.x
                    and c.bbox_y == elem.bounding_box.y
                    and c.type == elem.type
                ):
                    c.was_chosen = True
                    trace.winner_rank = c.rank
                    trace.winner_source = c.source
                    break

            bb = elem.bounding_box
            cx = bb.x + bb.width // 2
            cy = bb.y + bb.height // 2
            trace.winner_coords_x = cx
            trace.winner_coords_y = cy

            # Dispatch the correct mouse/keyboard action
            if ".fill(" in line:
                trace.action_dispatched = "fill"
                m = re.search(r'\.fill\("([^"]*)"\)', line)
                value = m.group(1) if m else ""
                # Primary: JS direct-set — more reliable than keyboard after a locator timeout
                try:
                    filled = await page.evaluate(
                        """([cx, cy, val]) => {
                            const el = document.elementFromPoint(cx, cy);
                            if (el && (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA')) {
                                el.focus();
                                el.value = val;
                                el.dispatchEvent(new InputEvent('input', {bubbles: true, data: val}));
                                el.dispatchEvent(new Event('change', {bubbles: true}));
                                return true;
                            }
                            return false;
                        }""",
                        [cx, cy, value],
                    )
                except Exception:
                    filled = False
                if not filled:
                    await page.mouse.click(cx, cy)
                    await page.wait_for_timeout(150)
                    await page.keyboard.press("Control+a")
                    await page.keyboard.type(value, delay=10)

            elif ".clear()" in line:
                trace.action_dispatched = "clear"
                await page.mouse.click(cx, cy)
                await page.keyboard.press("Control+a")
                await page.keyboard.press("Delete")

            elif ".check()" in line or ".uncheck()" in line:
                trace.action_dispatched = "check" if ".check()" in line else "uncheck"
                want_checked = ".check()" in line
                already_correct = await page.evaluate(
                    """([cx, cy, want]) => {
                        const el = document.elementFromPoint(cx, cy);
                        if (el && el.tagName === 'INPUT' &&
                            (el.type === 'checkbox' || el.type === 'radio')) {
                            return el.checked === want;
                        }
                        return false;
                    }""",
                    [cx, cy, want_checked],
                )
                if not already_correct:
                    await page.mouse.click(cx, cy)

            elif ".select_option(" in line:
                trace.action_dispatched = "select_option"
                m = re.search(r'\.select_option\((?:label=)?"([^"]*)"\)', line)
                value = m.group(1) if m else ""
                await page.mouse.click(cx, cy)
                await page.wait_for_timeout(300)
                if value:
                    await page.keyboard.type(value)
                    await page.keyboard.press("Enter")

            elif ".hover()" in line:
                trace.action_dispatched = "hover"
                await page.mouse.move(cx, cy)

            elif ".click" in line:
                trace.action_dispatched = "click"
                await page.mouse.click(cx, cy)
                await page.wait_for_load_state("networkidle", timeout=5000)

            else:
                trace.success = False
                return trace

            logger.info(
                "Visual fallback: '%s' → %s(%s) at (%d, %d) conf=%.2f src=%s",
                target, elem.type, elem.texte_ocr or elem.label,
                cx, cy, elem.confiance_detection, elem.source,
            )
            trace.success = True
            return trace

        except Exception as e:
            logger.debug("Visual fallback error: %s", e)
            trace.success = False
            return trace

    async def _exec_line(self, page: Page, line: str):
        """Execute a single Playwright line dynamically."""
        line = line.strip()
        if not line or line.startswith("#"):
            return

        # Build a safe local namespace with page and expect
        local_ns = {"page": page, "expect": expect, "re": __import__("re")}
        # Wrap in an async function for await support
        code = f"async def __exec(_page, _expect, _re):\n"
        code += f"    page = _page\n"
        code += f"    expect_fn = _expect\n"

        # Replace expect( with expect_fn( to avoid shadowing
        exec_line = line.replace("expect(", "expect_fn(")
        code += f"    {exec_line}\n"

        compiled = compile(code, "<playwright_step>", "exec")
        exec(compiled, local_ns)
        await local_ns["__exec"](page, expect, __import__("re"))

    async def _screenshot(self, page: Page, test_id: str, label: str) -> str:
        """Capture un screenshot et retourne le chemin."""
        try:
            filename = f"{test_id}_{label}.png"
            filepath = os.path.join(settings.SCREENSHOTS_DIR, filename)
            await page.screenshot(path=filepath, full_page=False)
            return filepath
        except Exception:
            return ""
